<?php

namespace JohnesKe\MpesaPhpApi;

use GuzzleHttp\Client;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\ServerException;
use Illuminate\Support\Facades\Route;

use JohnesKe\MpesaPhpApi\Exceptions\MpesaPhpApiRequestException;
use JohnesKe\MpesaPhpApi\Logging\Log;

class MpesaPhpApiHttpClient
{
    const BASE_DOMAIN            = "safaricom.co.ke";

    const BASE_SANDBOX_DOMAIN    = "https://sandbox." . self::BASE_DOMAIN;

    const BASE_PRODUCTION_DOMAIN = "https://api." . self::BASE_DOMAIN;

    protected $tokenUrl = '/oauth/v1/generate?grant_type=client_credentials';

    protected $stkUrl   = '/mpesa/stkpush/v1/processrequest';

    protected $baseDomain;

    protected $tokenClient;

    /**
     * Guzzle client initialization.
     *
     * @var Client
     */
    protected $client;

    /**
     * Safaricom MPESA APIs application consumer key.
     *
     * @var string
     */
    protected $consumerKey;

    /**
     * Safaricom MPESA APIs application consumer secret.
     *
     * @var string
     */
    protected $consumerSecret;

    /**
     * Access token generated by Safaricom MPESA APIs.
     *
     * @var string
     */
    protected $accessToken;

    /**
     * Identifier organization Map on Safaricom MPESA APIs.
     *
     * @var array
     */
    protected $identifier = [
        'msisdn' => '1', // MSISDN
        'till' => '2', // Till Number
        'paybill' => '4', // Shortcode
    ];

    /**
     * Base URL end points for the Safaricom APIs.
     *
     * @var array
     */
    protected $base_url = [
        'sandbox' => 'https://sandbox.safaricom.co.ke',
        'live' => 'https://api.safaricom.co.ke',
    ];


    /**
     * Make the initializations required to make calls to the Safaricom MPESA APIs
     * and throw the necessary exception if there are any missing required
     * configurations.
     */
    function __construct( $environment, $consumer_key , $consumer_secret ){

        if($environment === 'sandbox') {
            $this->baseDomain = self::BASE_SANDBOX_DOMAIN;

        } elseif($environment === 'live') {
            $this->baseDomain = self::BASE_PRODUCTION_DOMAIN;
        }

        $credentials = base64_encode($consumer_key.':'.$consumer_secret);

        $this->tokenClient = new Client([
            'base_uri' => $this->baseDomain,
            'headers' => [
                'Accept' => 'application/json',
                'Authorization' => 'Basic '.$credentials
            ]
        ]);

        $this->validateConfigurations();

        $mode = config('mpesa-php-api.mode');

        $options = [
            'base_uri' => $this->base_url[$mode],
            'verify' => $mode === 'sandbox' ? false : true,
        ];

        if (config('mpesa-php-api.logs.enabled')) {
            $options = Log::enable($options);
        }

        $this->client = new Client($options);
        $this->consumerKey = config('mpesa-php-api.consumer_key');
        $this->consumerSecret = config('mpesa-php-api.consumer_secret');
        $this->getAccessToken();

    }

    /**
     * Check if it contains a route name and return full route or
     * return the string assuming its a full URL.
     *
     * @param $urlConfig
     * @return string
     */
    protected function setUrl($urlConfig)
    {
        return Route::has($urlConfig) ? route($urlConfig) : $urlConfig;
    }

    /**
     * Get access token from Safaricom MPESA APIs.
     *
     * @return mixed
     */
    protected function getAccessToken()
    {
        // Set the auth option
        $options = [
            'auth' => [
                $this->consumerKey,
                $this->consumerSecret,
            ],
        ];

        $accessTokenDetails = $this->call('oauth/v1/generate?grant_type=client_credentials', $options, 'GET');
        $this->accessToken = $accessTokenDetails->access_token;
    }

    /**
     * Validate configurations.
     */
    protected function validateConfigurations()
    {
        // Validate keys
        if (empty(config('mpesa-php-api.consumer_key'))) {
            throw new \InvalidArgumentException('Consumer key has not been set.');
        }
        if (empty(config('mpesa-php-api.consumer_secret'))) {
            throw new \InvalidArgumentException('Consumer secret has not been set');
        }
    }

    /**
     * Generate encrypted security credential.
     *
     * @param $plaintext
     * @return string
     * @internal param null|string $password
     */
    protected function securityCredential($plaintext)
    {
        $publicKey = file_get_contents(__DIR__.'/../cert.cer');

        openssl_public_encrypt($plaintext, $encrypted, $publicKey, OPENSSL_PKCS1_PADDING);

        return base64_encode($encrypted);
    }

    /**
     * Make API calls to Safaricom MPESA APIs.
     *
     * @param string $url
     * @param array $options
     * @param string $method
     * @return mixed
     * @throws MpesaPhpApiRequestException
     */
    protected function call($url, $options = [], $method = 'POST')
    {
        if (isset($this->accessToken)) {
            $options['headers'] = ['Authorization' => 'Bearer '.$this->accessToken];
        }

        try {
            $response = $this->client->request($method, $url, $options);

            $stream = $response->getBody();
            $stream->rewind();
            $content = $stream->getContents();

            return json_decode($content);

        } catch (ServerException $e) {

            $response = json_decode($e->getResponse()->getBody()->getContents());

            if (isset($response->Envelope)) {
                $message = 'Mpesa Php APIs: '.$response->Envelope->Body->Fault->faultstring;
                throw new MpesaPhpApiRequestException($message, $e->getCode());
            }
            throw new MpesaPhpApiRequestException('Mpesa Php APIs: '.$response->errorMessage, $e->getCode());

        } catch (ClientException $e) {

            $response = json_decode($e->getResponse()->getBody()->getContents());

            throw new MpesaPhpApiRequestException('Mpesa Php APIs: '
                .$response->errorMessage, $e->getCode());
        }
    }

}
